web/api/urls.py
from django.urls import path, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from .v1 import api_view

schema_view = get_schema_view(
   openapi.Info(
      title="Askme API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('v1/api/list', api_view.list_questions, name='api_list_questions'),
    path('v1/api/user', api_view.user, name='api_list_user'),
    path('v1/api/search/<str:text>', api_view.search, name='api_search'),
    path('v1/api/question/<int:question_id>', api_view.question_by_id),
    path('v1/api/answers/<int:question_id>', api_view.get_answers_for_question,
         name='api_get_answers_for_question'),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$',
            schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0),
            name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0),
            name='schema-redoc'),
]

web/askme/urls.py
import mimetypes

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

mimetypes.add_type("application/javascript", ".js", True)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include("question.urls")),
    path('', include("user.urls")),
    path('', include("api.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/question/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('ask/', views.AskmeMultiFormView.as_view(), name='ask'),
    path('', views.HomeRedirectView.as_view(), name='home'),
    path('likepost/', views.LikePostView.as_view(), name='likepost'),
    path('question/', views.QListView.as_view(), name='list_all_questions'),
    path('question/<int:question_id>', views.ShowQuestionView.as_view(),
         name='show_question'),
    path('query/', views.QueryRequestListView.as_view(),
         name='list_queried_questions'),
    path('tag/', views.QueryTagListView.as_view(),
         name='list_questions_by_tag'),
]

web/common/models.py
from django.db import models
from user.models import User


# Create your models here.
class Tag(models.Model):
    tag = models.CharField(max_length=256, null=True, blank=True,
                           default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class CreateQuestion(models.Model):
    title = models.CharField(max_length=256)
    description = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    tag = models.ManyToManyField(Tag)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

web/question/models.py
from common.models import CreateQuestion
from django.db import models
from user.models import User


class CreateAnswer(models.Model):
    description = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    question = models.ForeignKey(CreateQuestion, on_delete=models.CASCADE)


class QuestionVote(models.Model):
    class QuestionVoteType(models.IntegerChoices):
        INDIFFERENCE = 0, 'indiffence'
        CONDEMN = 1, 'condemn'
        APPROVE = 2, 'approve'

    author = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(CreateQuestion, on_delete=models.CASCADE)
    type_id = models.PositiveSmallIntegerField(
        choices=QuestionVoteType.choices,
        default=QuestionVoteType.INDIFFERENCE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class AnswerVote(models.Model):
    class AnswerVoteType(models.IntegerChoices):
        INDIFFERENCE = 0, 'indiffence'
        CONDEMN = 1, 'condemn'
        APPROVE = 2, 'approve'
        RIGHT = 3, 'right'

    author = models.ForeignKey(User, on_delete=models.CASCADE)
    answer = models.ForeignKey(CreateAnswer, on_delete=models.CASCADE)
    type_id = models.PositiveSmallIntegerField(
        choices=AnswerVoteType.choices, default=AnswerVoteType.INDIFFERENCE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

web/question/forms.py
from betterforms.multiform import MultiModelForm
from common.models import CreateQuestion, Tag
from django import forms
from django.forms import ModelForm


class ListQuestionsForm(forms.ModelForm):
    class Meta:
        model = CreateQuestion
        fields = '__all__'


class CreateAnswerForm(forms.ModelForm):
    class Meta:
        model = CreateQuestion
        fields = ('description',)


class AskQuestionForm(forms.ModelForm):
    class Meta:
        model = CreateQuestion
        fields = ('title', 'description')


class TagForm(ModelForm):
    class Meta:
        model = Tag
        fields = ('tag',)

    def clean_tag(self):
        data = self.cleaned_data['tag'].split(',')[:3]
        return data

    def save(self):
        data = self.cleaned_data
        list_result = []
        for i_data in data['tag']:
            current_tag = Tag(tag=i_data)
            current_tag.save()
            list_result.append(current_tag)
        return list_result


class AskMeMultiForm(MultiModelForm):
    form_classes = {
            'ask_form': AskQuestionForm,
            'tag_form': TagForm,
        }

web/question/views.py
from askme.settings import EMAIL_FROM
from common.library import (generate_trading, popular_answers,
                            popular_questions, search_html)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.core.paginator import Paginator
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect
from django.views import View
from django.views.generic import CreateView, ListView
from django.views.generic.detail import SingleObjectMixin

from .forms import AskMeMultiForm, AskQuestionForm, CreateAnswerForm, TagForm
from .models import AnswerVote, CreateAnswer, CreateQuestion, QuestionVote

# Create your views here.


class HomeRedirectView(LoginRequiredMixin, ListView):
    login_url = '/login'
    redirect_field_name = 'home'

    def get(self, request):
        if 'searchField' in request.GET.keys() and request.GET['searchField']:
            return HttpResponseRedirect(
                f"/query?searchField={request.GET['searchField']}")
        else:
            questions = popular_questions()
            paginator = Paginator(questions, 20)

            page_number = request.GET.get('page')
            page_obj = paginator.get_page(page_number)
            return search_html(request, "question/home.html",
                               {"page_obj": page_obj})


class TradingMixin(object):
    def get_context_data(self, **kwargs):
        try:
            context = super().get_context_data(**kwargs)
        except Exception:
            context = {}
        return generate_trading(self.request, context)


class QListView(TradingMixin, LoginRequiredMixin, ListView):
    login_url = '/login'
    redirect_field_name = 'list_all_questions'
    # queryset = popular_questions() # из-за этой строки makemigrations падала
    # с ошибкой. В качестве решения создал get_queryset
    context_object_name = 'form'
    template_name = "question/list.html"

    def get_queryset(self, *args, **kwargs):
        return popular_questions()


class ShowQuestionView(View):
    def get(self, request, question_id):
        question = CreateQuestion.objects.get(pk=question_id)
        question_unlike = False
        question_like = False
        try:
            question_vote = QuestionVote.objects.get(author=request.user,
                                                     question=question)
            if question_vote.type_id == QuestionVote.QuestionVoteType.CONDEMN:
                question_unlike = True
            elif question_vote.type_id == (
                    QuestionVote.QuestionVoteType.APPROVE
                    ):
                question_like = True
        except Exception:
            pass
        answer_form = CreateAnswerForm()
        paginator = Paginator(popular_answers(question), 30)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        return search_html(request,
                           "question/show_question.html",
                           {"question": question,
                            "answer_form": answer_form,
                            "page_obj": page_obj,
                            "question_unlike": question_unlike,
                            "question_like": question_like,
                            "count_question_like": self.get_count_like(
                                question),
                            "count_question_unlike": self.get_count_unlike(
                                question)
                            })

    def get_count_like(self, question):
        try:
            count_question_like = QuestionVote.objects.filter(
                question=question,
                type_id=QuestionVote.QuestionVoteType.APPROVE).count()
        except Exception:
            count_question_like = 0
        return count_question_like

    def get_count_unlike(self, question):
        try:
            count_question_unlike = QuestionVote.objects.filter(
                question=question,
                type_id=QuestionVote.QuestionVoteType.CONDEMN).count()
        except Exception:
            count_question_unlike = 0
        return count_question_unlike

    def post(self, request, question_id):
        question = CreateQuestion.objects.get(pk=question_id)
        if 'question_like' in request.POST:
            try:
                question_vote = QuestionVote.objects.get(author=request.user,
                                                         question=question)
                question_vote.type_id = (
                    QuestionVote.QuestionVoteType.INDIFFERENCE
                    )
                if request.POST['question_like'] == 'unlike':
                    question_vote.type_id = (
                        QuestionVote.QuestionVoteType.CONDEMN
                        )
                if request.POST['question_like'] == 'like':
                    question_vote.type_id = (
                        QuestionVote.QuestionVoteType.APPROVE
                        )
                question_vote.save()
            except Exception:
                if request.method == 'POST':
                    if request.POST['question_like'] == 'unlike':
                        question_vote = QuestionVote(
                            author=request.user,
                            question=question,
                            type_id=QuestionVote.QuestionVoteType.CONDEMN
                        )
                        question_vote.save()
                    elif request.POST['question_like'] == 'like':
                        question_vote = QuestionVote(
                            author=request.user,
                            question=question,
                            type_id=QuestionVote.QuestionVoteType.APPROVE
                        )
                        question_vote.save()
        if "description" in request.POST:
            answer_form = CreateAnswerForm(request.POST)
            if answer_form.is_valid():
                answer = CreateAnswer(author=request.user,
                                      description=request.POST['description'],
                                      question=question)
                answer.save()
                subject = f"There is new answer for /question/ {question_id}"
                body = f"""
                author:{request.user.username}
                send new answer:
                {request.POST['description'][:120]}
                for your question:
                {question.title[:120]}
                {question.description[:120]}
                """
                send_mail(
                    subject=subject,
                    message=body,
                    from_email=EMAIL_FROM,
                    recipient_list=[question.author.email], fail_silently=False
                )
        return HttpResponseRedirect(f"/question/{question_id}")


class QueryTagListView(TradingMixin, LoginRequiredMixin, SingleObjectMixin,
                       ListView):
    login_url = '/login'
    redirect_field_name = 'list_questions_by_tag'
    template_name = "question/list.html"
    model = CreateQuestion
    paginate_by = 20
    context_object_name = 'form'

    def get(self, request, *args, **kwargs):
        self.object = CreateQuestion.objects.filter(
            tag__tag=request.GET['name'])
        return super().get(request, *args, **kwargs)

    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(
            tag__tag=self.request.GET['name']
        )


class QueryRequestListView(TradingMixin, LoginRequiredMixin, SingleObjectMixin,
                           ListView):
    login_url = '/login'
    redirect_field_name = 'list_queried_questions'
    template_name = "question/list.html"
    model = CreateQuestion
    paginate_by = 20
    context_object_name = 'form'

    def get(self, request, *args, **kwargs):
        self.object = CreateQuestion.objects.filter(
            title__contains=self.request.GET['searchField'])
        return super().get(request, *args, **kwargs)

    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(
            title__contains=self.request.GET['searchField']
        )


class AskmeMultiFormView(TradingMixin, LoginRequiredMixin, CreateView):
    form_class = AskMeMultiForm
    redirect_field_name = 'ask'
    success_url = "/ask"
    login_url = '/login'
    template_name = "question/ask_question_multi_form.html"

    def form_valid(self, form):
        tag = form['tag_form'].save()
        question = CreateQuestion(
                author=self.request.user,
                title=self.request.POST['ask_form-title'],
                description=self.request.POST['ask_form-description'])
        question.save()
        for i_tag in tag:
            question.tag.add(i_tag)
        return redirect(self.success_url)


class AskMeListView(TradingMixin, LoginRequiredMixin, ListView):
    # TODO класс не используется, я его сохранил на память, чтобы знать что
    #  можно вызывывать post через get для сокращения кода
    login_url = '/login'
    redirect_field_name = 'ask'
    tag_form_class = TagForm
    ask_form_class = AskQuestionForm

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def post(self, request):
        post_data = request.POST or None
        ask_form = self.ask_form_class(post_data)
        tag_form = self.tag_form_class(post_data)
        template_name = "question/ask_question.html"
        if ask_form.is_valid() and tag_form.is_valid():
            tag = tag_form.save()

web/question/templates/question/ask_question.html
{% extends 'question/search.html' %}
{% load crispy_forms_tags %}
{% block title %} AskMe {% endblock %}
{% block script %}
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
  <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
      <script>
  $( function() {
    var availableTags = [
      "ActionScript",
      "AppleScript",
      "Asp",
      "BASIC",
      "C",
      "C++",
      "Clojure",
      "COBOL",
      "ColdFusion",
      "Erlang",
      "Fortran",
      "Groovy",
      "Haskell",
      "Java",
      "JavaScript",
      "Lisp",
      "Perl",
      "PHP",
      "Python",
      "Ruby",
      "Scala",
      "Scheme"
    ];
    $( "#id_tag" ).autocomplete({
      source: availableTags
    });
  } );
  </script>
 {% endblock %}
{% block auth_content %}
<h2> Ask a question </h2>
<form method="POST">
    {% csrf_token %}
    <div class="form-style {% if form.title.errors %} error {% endif %} ">
        {{form.title.errors}}
        {{form.title | as_crispy_field}}
    </div>

    <div class="form-style {% if form.description.errors %} error {% endif %} ">
        {{form.description.errors}}
        {{form.description | as_crispy_field}}
    </div>

    <div class="form-style {% if tag_form.tag.errors %} error {% endif %} ">
        {{tag_form.tag.errors}}
        {{tag_form.tag | as_crispy_field}}
    </div>


    <button class=" btn btn-lg btn-primary">Ask!</button>
</form>
{% endblock %}

web/question/templates/question/ask_question_multi_form.html
{% extends 'question/search.html' %}
{% load crispy_forms_tags %}
{% block title %} AskMe {% endblock %}
{% block script %}
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
  <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
      <script>
  $( function() {
    var availableTags = [
      "ActionScript",
      "AppleScript",
      "Asp",
      "BASIC",
      "C",
      "C++",
      "Clojure",
      "COBOL",
      "ColdFusion",
      "Erlang",
      "Fortran",
      "Groovy",
      "Haskell",
      "Java",
      "JavaScript",
      "Lisp",
      "Perl",
      "PHP",
      "Python",
      "Ruby",
      "Scala",
      "Scheme"
    ];
    $( "#id_tag" ).autocomplete({
      source: availableTags
    });
  } );
  </script>
 {% endblock %}
{% block auth_content %}
<h2> Ask a question </h2>
<form method="POST">
    {% csrf_token %}
    <div class="form-style {% if form.title.errors %} error {% endif %} ">
        {{form.ask_form.title.errors}}
        {{form.ask_form.title | as_crispy_field}}
    </div>

    <div class="form-style {% if form.description.errors %} error {% endif %} ">
        {{form.ask_form.description.errors}}
        {{form.ask_form.description | as_crispy_field}}
    </div>

    <div class="form-style {% if tag_form.tag.errors %} error {% endif %} ">
        {{form.tag_form.tag.errors}}
        {{form.tag_form.tag | as_crispy_field}}
    </div>


    <button class=" btn btn-lg btn-primary">Ask!</button>
</form>
{% endblock %}

web/question/templates/question/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
<link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <title>  {% block title %} {% endblock %}  </title>
<link rel="shortcut icon" type="image/x-icon" href="/static/logo/logo.jpg">

{% block script %} {% endblock %}
</head>
<body>
    {% block top %} {% endblock %}
   {% block content %} {% endblock %}
</body>
</html>

web/question/templates/question/home.html
{% extends 'question/search.html' %}


{% block auth_content %}

    {% for i_question in page_obj %}
        <h5><a href="/question/{{i_question.id|cut:" "}}">
        {{ i_question.id|upper}} {{ i_question.title|upper }}<br></a></h5>
        <p style="text-align:right;">{{ i_question.author }}</p>
        <br>
        <blockquote class="blockquote">
        {{ i_question.description }}</blockquote>
        {% for i_tag in i_question.tag.all %}
            <a href="/tag?name={{ i_tag.tag }}">{{ i_tag.tag }}</a>
            <br>
        {% endfor %}
        <hr nodashed size="1px" style="border:dotted">
    {% endfor %}

    <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
    </div>
{% endblock %}

web/question/templates/question/is_auth.html
{% extends 'question/search.html' %}

{% block content %}
{% endblock %}

web/question/templates/question/list.html
{% extends 'question/search.html' %}

{% block title %} AskMe {% endblock %}

{% block auth_content %} <h2> Questions </h2>
<ol>
    {% for i_question in form %}

    <li>Title: {{i_question.title}} <br> Question: {{i_question.description}}
        <br>
        <div> Author:
        {{i_question.author}}
        <br>
        Tags:
        {% for i_tag in i_question.tag.all %}
            <a href="/tag?name={{i_tag.tag}}">{{i_tag.tag}}</a>
            <br>
        {% endfor %}
    </div> </li>



{% endfor %}
</ol>
{% endblock %}

web/question/templates/question/load_file.html
{% block content %}
    <h2>Загрузите файл</h2>
    <form method="post" enctype="multipart/form-data" >
        {% csrf_token %}
        {{form}}
        <button type="submit">Загрузить</button>
    </form>
{% endblock %}

web/question/templates/question/not_found.html
{% extends 'question/search.html' %}

{% block title %} AskMe {% endblock %}

{% block content %} <h2> Questions </h2>
<p> We couldn't find anything for '{{ query_word }}'</p>
{% endblock %}

web/question/templates/question/search.html
{% extends 'question/base.html' %}

{% block top %}

    <a href="/">
        <img src="/static/logo/logo.jpg" alt="logo" height="3%" width="3%"
             style="float:left"></a>
    <form id="searchForm" style="text-align:center;">

        <label for="sea">Search for : </label>
        <input type="search" name="searchField"/>
        <input type="submit" value="Search" class=" btn btn-small btn-primary"/>
    </form>

    {% if user.is_authenticated %}
        <div style="float:right; padding: 30px" >
        <nav class="navbar bg-light">
        <ul class="nav" >


           <li class="nav-item"> <a href="/settings"><img src="/avatars/{{ avatar.image }}"
                             alt="current_avatar"
                 height="40"   width="40" ></a></li>
                <li class="nav-item"><a href="/settings" class="nav-link"
                >{{ user.username }}</a></li>
                <li class="nav-item"><a href="{% url 'ask' %}" class="nav-link">Ask question</a></li>
                <li class="nav-item"><a href="{% url 'logout' %}" class="nav-link">Log Out</a></li>
                <li class="nav-item"><a href="/signup" class="nav-link">Регистрация</a></li>
            </ul></nav>



        </div>
        <br>
        <br>
        <br>
        <br>
        <hr>
    {% else %}
        <p style="text-align:right;"><a href="/signup">Регистрация</a></p>
        <p style="text-align:center;">Вы не залогинены
            <a href="{% url 'login' %}">Log In</a></p>
    {% endif %}


{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
        <div style="display:block; width:100%;">
        <div style="width:50%; float: left; display: inline-block;">
            {% block auth_content %}
        {% endblock %}
        </div>
            <div style="width:50%; float: left; display: inline-block;
            padding-left: 15px" class="list-group">

            <p style="text-align:center;">Trending:</p>

            {% if is_trending %}
{#                <ol class="list-group list-group-numbered">#}
                {% for j_question in trending %}
{#                    <li class="list-group-item d-flex justify-content-between align-items-start">#}
                    <a href="/question/{{j_question.id|cut:" "}}" class="list-group-item list-group-item-action active">
        {{ j_question.id|upper}} {{ j_question.title|upper }}<br></a>
{#                </li>#}
                {% empty %}
                <li>Sorry, there aren't questions.</li>
                {% endfor %}
{#                </ol>#}
                {% else %}
                <li>Sorry, there aren't questions.</li>
                {% endif %}
        </div>
        </div>
    {% endif %}
{% endblock %}

web/question/templates/question/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hello</title>
</head>
<body>
 Hello, {{ user.username }}
<p> user.is_authenticated: {{ user.is_authenticated }}</p>
{% if user.is_authenticated %}
    <p> You are log in as {{ user.first_name }} {{ user.last_name }}</p>
{% endif %}
</body>
</html>

web/question/templates/question/user_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <title>Title</title>
</head>
<body class="container">
<ul class="list-group">
    <li class="list-group-item">
        User {{ user }}
    </li>
        <li class="list-group-item">
            <a href="{% url 'home' %}"></a>
    </li>
</ul>
{% block content %} {% endblock %}
</body>
</html>